apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaverso
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: metaverso
  template:
    metadata:
      labels:
        app: metaverso
    spec:
      containers:
      - name: metaverso
        # L'immagine che abbiamo buildato nello script
        image: ecofoodchain/metaverso:latest
        # Usa l'immagine locale, non cercare su Docker Hub
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: metaverso
spec:
  type: ClusterIP 
  selector:
    app: metaverso 
  ports:
    - protocol: TCP
      port: 80 # Porta del servizio 
      targetPort: 80 # Porta del container 