apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # non va bene: dobbiamo usare EFS 
  # NOTE: hostPath used for prototype reproducibility; in future work this
  # will be replaced with LocalStack-backed persistent storage
  hostPath:
    path: "/tmp/fabric-network"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi