apiVersion: v1
kind: Service
metadata:
  name: orderer
spec:
  selector:
    app: orderer
  ports:
    - port: 7050
      targetPort: 7050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:2.5
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        command: ["orderer"]
        env:
        - name: FABRIC_LOGGING_SPEC
          value: "INFO"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: "file"
        - name: ORDERER_GENERAL_GENESISFILE
          value: "/fabric/channel-artifacts/genesis.block"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp"
        # --- FIX IDENTITÃ€ ---
        - name: ORDERER_GENERAL_LOCALMSPID
          value: "OrdererMSP"
        # --- TLS CONFIG ---
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
        volumeMounts:
        - mountPath: /fabric
          name: fabric-data
      volumes:
      - name: fabric-data
        persistentVolumeClaim:
          claimName: fabric-pvc