apiVersion: apps/v1
kind: Deployment
metadata:
  name: filiera-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filiera-frontend
  template:
    metadata:
      labels:
        app: filiera-frontend
    spec:
      containers:
      - name: filiera-frontend
        image: ecofoodchain/filiera-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
