apiVersion: apps/v1
kind: Deployment
metadata:
  name: filiera-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filiera-middleware
  template:
    metadata:
      labels:
        app: filiera-middleware
    spec:
      containers:
      - name: filiera-middleware
        image: ecofoodchain/filiera-middleware:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3000"
        - name: DISCOVERY_AS_LOCALHOST
          value: "false"
        - name: CCP_PATH
          value: "/fabric/connection-org1.json"
        - name: WALLET_PATH
          value: "/fabric/wallet"
        volumeMounts:
        - mountPath: /fabric
          name: fabric-data
      volumes:
      - name: fabric-data
        persistentVolumeClaim:
          claimName: fabric-pvc
