apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
      - name: chatbot-frontend
        image: ecofoodchain/chatbot-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
